server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
